remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  theme: jekyll-theme-dinky
  enabled: true
  collections: true
include:
  - Readme.md
